server.port=8081

# JWT settings (Must match auth-service)
jwt.secret=9a65a3962b166ffaa931e9c562e87c08a478b0e8c459ea7916bfdf7693994344

# NGO Service Route (Secured)
spring.cloud.gateway.server.webflux.routes[0].id=ngo-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/ngos/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=AuthenticationFilter

# Donation Service Route (Secured)
spring.cloud.gateway.server.webflux.routes[1].id=donation-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/donations/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=AuthenticationFilter

# Auth Service Route (Public)
spring.cloud.gateway.server.webflux.routes[2].id=auth-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/auth/**
